### ISSUE TITLE
suggestion] add a video demo

### ISSUE THREAD

**Issue by reihanboo** [SpaceWalkerRS/world-cutters#1]
this mod _sounds_ fun, but i dont see a demo.
and from my pov, a video demo usually = higher chance of me downloading a mod

**Comment by TCL03-HCMUT** [comment]
Technically there's this video https://www.youtube.com/watch?v=Bd0edHzMRAs

**Comment by SpaceWalkerRS** [comment]
It's a really small, simple mod. The Modrinth page and the video linked above showcase pretty much everything there is to know about it.

**Comment by DarianLStephens** [comment]
I'm glad I watched that video, because I assumed that you'd need to push a block in to the position above a stonecutter, and that's the only place it would work. Also that it would break it over time, not instantly.
So, it was nice to have that extra context, to know what this mod does in more detail.

Until I saw this issue, I was prepared to start looking at the source code to try and figure out exactly how it works before adding it to my game.
